const { chromium } = require('playwright-core')
async function main() {
  const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  const errors = []
  page.on('response', r => { if (r.status() >= 500) errors.push(`${r.url()} → ${r.status()}`) })
  await page.goto('http://localhost:5173', { waitUntil: 'networkidle' })
  await page.evaluate(() => localStorage.clear())
  await page.reload({ waitUntil: 'networkidle' })
  await page.locator('input.input').nth(0).fill('yaozhi_student13')
  await page.locator('input.input').nth(1).fill('DEMO2026')
  await page.locator('button:has-text("进入药知")').click()
  await page.waitForSelector('text=使用前，请阅读并同意以下文档', { timeout: 8000 })
  const cards = page.locator('button.rounded-2xl')
  await cards.nth(0).click(); await cards.nth(1).click()
  await page.locator('div.rounded-2xl:has-text("知情同意书") button').first().click()
  await page.locator('button:has-text("进入学习")').click()
  await page.waitForSelector('text=你这个阶段最想解决什么', { timeout: 8000 })
  await page.locator('button:has-text("保存目标，开始摸底")').click()
  await page.waitForSelector('text=交卷并生成画像', { timeout: 8000 })
  const opts = page.locator('.card button.rounded-xl')
  for (let i = 0; i < await opts.count(); i++) await opts.nth(i).click()
  await page.locator('button:has-text("交卷并生成画像")').click()
  await page.waitForSelector('text=识别到的薄弱项', { timeout: 8000 })
  await page.locator('button:has-text("进入今日待办")').click()
  await page.waitForSelector('text=开始练习', { timeout: 8000 })
  await page.locator('button:has-text("开始练习")').first().click()
  await page.waitForSelector('text=提交答案', { timeout: 8000 })
  await page.locator('button:has(span:text-is("A"))').first().click()
  await page.locator('button:has-text("提交答案")').click()
  await page.waitForSelector('text=错因诊断卡', { timeout: 8000 })
  const hasRefineBtn = await page.locator('button:has-text("追问对话")').count()
  const levelLow = await page.getByText('证据等级 · 低').count()
  await page.screenshot({ path: 'v3-card-first.png' })
  let hasFu = 0, levelHigh = 0
  if (hasRefineBtn) {
    await page.locator('button:has-text("追问对话")').click()
    await page.waitForSelector('text=定向追问', { timeout: 8000 })
    hasFu = 1
    await page.fill('.card:has-text("定向追问") textarea', '阿托品阻断 M 受体导致散瞳，毛果芸香碱激动 M 受体导致缩瞳')
    await page.locator('button:has-text("提交回答")').click()
    await page.waitForTimeout(1000)
    await page.locator('.card:has-text("定向追问") button.rounded-2xl').first().click()
    await page.waitForTimeout(1500)
    levelHigh = await page.getByText('证据等级 · 高').count()
    await page.screenshot({ path: 'v3-refined.png' })
  }
  console.log(JSON.stringify({ hasRefineBtn, levelLow, hasFu, levelHigh, api5xx: errors }))
  await browser.close()
}
main().catch(e => { console.error(String(e).slice(0, 300)); process.exit(1) })
